name: "github-ejs-build"
on: 
  workflow_dispatch:
    inputs:
      art_server_id:
        required: true
        type: string
        default: "soleng"
        description: "Artifactory Server ID"
      art_repo_id:
        required: true
        type: string
        default: "carm-npm-dev"
        description: "Artifactory Repository Name"
      art_project:
        required: true
        type: string
        default: "carm"
        description: "Artifactory Project ID"
      art_docker_registry:
        required: true
        type: string
        default: "soleng.jfrog.io/carm-docker-dev/"
        description: "Artifactory Docker Registry"
      art_docker_image:
        required: true
        type: string
        default: "ejs"
        description: "Docker Image name"
jobs:
  build:
    runs-on: ubuntu-latest
    # Here we install all the tools : docker buildx, QEMU, JDK 11, JFrog CLI
    steps:
      - name: Print Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install Node
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
            JFROG_CLI_BUILD_PROJECT: ${{ github.event.inputs.art_project }}
            JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      - name: Ping JFrog CLI
        run: jf rt ping
      
      - name: NPM Audit 
        env:
          JFROG_CLI_BUILD_NAME: 'github-ejs-demo'
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
        run: |
          jf rt bce ${{ env.JFROG_CLI_BUILD_NAME }} $GITHUB_RUN_NUMBER
          jf rt bag ${{ env.JFROG_CLI_BUILD_NAME }} $GITHUB_RUN_NUMBER
          jf npmc --server-id-resolve=${{ github.event.inputs.art_server_id }} --server-id-deploy=${{ github.event.inputs.art_server_id }} --repo-resolve=${{ github.event.inputs.art_repo_id }} --repo-deploy=${{ github.event.inputs.art_repo_id }}
          jf npm i --omit dev --build-name=${{ env.JFROG_CLI_BUILD_NAME }} --build-number=$GITHUB_RUN_NUMBER
          jf audit --npm

      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ github.event.inputs.art_docker_registry }}${{ github.event.inputs.art_docker_image }}:$GITHUB_RUN_NUMBER
      
      - name: Docker push 
        env:
          JFROG_CLI_BUILD_PROJECT: ${{ github.event.inputs.art_project }}
          JFROG_CLI_BUILD_NAME: 'github-ejs-demo'
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
          JF_HOST: ${{ secrets.JF_HOST }}
        run: |
          jf docker push ${{ github.event.inputs.art_docker_registry }}${{ github.event.inputs.art_docker_image }}:$GITHUB_RUN_NUMBER --server-id=${{ github.event.inputs.art_server_id }} --build-name=$JFROG_CLI_BUILD_NAME --build-number=$GITHUB_RUN_NUMBER          
          jf rt bp $JFROG_CLI_BUILD_NAME $GITHUB_RUN_NUMBER
